name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: "${{ secrets.VITE_SUPABASE_URL }}"
      VITE_SUPABASE_ANON_KEY: "${{ secrets.VITE_SUPABASE_ANON_KEY }}"
      VITE_API_URL: "${{ secrets.VITE_API_URL }}"
      VITE_POLAR_PRODUCT_40_ID: "9f6e6015-b9a6-4072-8a66-8f65ec91f4ee"
      VITE_POLAR_PRODUCT_100_ID: "41fc2810-bc8a-471e-8db4-5e1c4f39555c"
      VITE_POLAR_PRODUCT_200_ID: "a2bcad44-10b1-4144-a2d6-748bebbc2450"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
